### PR TITLE
[remote_transmitter] Fix BK7231N build by limiting the PWM path to BK7238

### PR DESCRIPTION
**Pull request by kbx81**
# What does this implement/fix?

Fixes a build regression from #18660 on BK7231N. Any BK7231N config using `remote_transmitter` currently fails to compile:

```
remote_transmitter_bk72xx.cpp:86:3: error: 'pwm_param_st' was not declared in this scope; did you mean 'pwm_param_t'?
remote_transmitter_bk72xx.cpp:91:7: error: 'pwm_init_param' was not declared in this scope
remote_transmitter_bk72xx.cpp:91:38: error: 'pwm_start' was not declared in this scope; did you mean 'pwm_ctrl'?
```

`REMOTE_TRANSMITTER_BK_PWM` was gated on the PWM peripheral: BK7231N and BK7238 share the shadow-register block with the hardware `CFG_UPDATA` load bit that the ISR path needs. That part is correct, but the *driver API* is not shared. LibreTiny builds the two families against different BDK snapshots: BK7238 gets one exposing `pwm_param_st` with `pwm_init_param()`/`pwm_start()`, while BK7231N gets an older one whose PWM driver offers only the `sddev_control` interface (`pwm_param_t`, `CMD_PWM_INIT_PARAM`) and does not declare those functions at all.

This narrows the gate to BK7238, the family the implementation was written and hardware-validated against. BK7231N returns to the generic bit-bang implementation it used before #18660, so it builds and behaves exactly as it did in 2026.8 and earlier — this is a restoration, not a new limitation. Adding BK7231N properly means implementing the `sddev_control` arming path, which needs hardware to validate; the reason it is excluded is now recorded at the top of `remote_transmitter_bk72xx.cpp` for whoever picks that up.

`_NON_BLOCKING_LIBRETINY_FAMILIES` drops BK7231N in the same commit. Leaving it would let `non_blocking: true` pass validation on a family whose header no longer declares `set_non_blocking`, turning a clear config error into a confusing compile error. No working configuration can regress here: on BK7231N the option only ever reached a translation unit that failed to compile.

Verified by compiling the reporter's exact configuration (`board: cb3s`, BK7231N) before and after — failing then succeeding — plus BK7238 hardware firmware, the `bk72xx-ard`, `rtl87xx-ard` and `esp8266-ard` component tests, an RTL8720C build with `non_blocking: true`, and the gate unit tests (BK7231N now asserts rejection). A BK7231N config with `non_blocking: true` now reports `non_blocking is only supported on ESP32, RTL8720C and BK7238` at validation time.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New developer-facing feature (adds functionality for component developers; no end-user configuration change)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) — [policy](https://developers.esphome.io/contributing/code/#what-constitutes-a-c-breaking-change)
- [ ] Developer breaking change (an API change that could break external components) — [policy](https://developers.esphome.io/contributing/code/#what-is-considered-public-c-api)
- [ ] Undocumented C++ API change (removal or change of undocumented public methods that lambda users may depend on) — [policy](https://developers.esphome.io/contributing/code/#c-user-expectations)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes <link to issue>

**Pull request in [esphome.io](https://github.com/esphome/esphome.io) with documentation (if applicable):**

- esphome/esphome.io#7319

**Pull request in [developers.esphome.io](https://github.com/developers.esphome.io) with developer documentation (if applicable):**

- esphome/developers.esphome.io#<developers.esphome.io PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040/RP2350
- [x] BK72xx
- [x] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml -- this failed to compile before, and builds now
bk72xx:
  board: cb3s

remote_transmitter:
  pin: P26
  carrier_duty_percent: 50%
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome.io](https://github.com/esphome/esphome.io).

### CODE REVIEW

**Review by esphbot — APPROVED** [review]
> [!TIP]
> No blocking issues found — ready to merge.

**Review by esphbot — APPROVED** [review]
> [!TIP]
> No blocking issues found — ready to merge.

**Review by swoboda1337 — APPROVED** [review]
