### PR TITLE
[esp32_hosted] Fix ESP32-P4 build without wifi, espnow or BLE

### LINKED ISSUE #19341: esp32_hosted: ESP32-P4 build fails on esp_now.h unless wifi/espnow/BLE is configured (2026.9.0)
### The problem

On 2026.9.0, an ESP32-P4 config using `esp32_hosted` fails to compile unless it
*also* happens to contain a `wifi:` block, the `espnow` component, or a
Bluetooth component:

    ../src/esphome/components/esp32_hosted/esp_now_hosted.cpp:33:10: fatal error: esp_now.h: No such file or directory

2026.9.0 added `esp_now_hosted.cpp` to `esp32_hosted`. It is guarded only by
`#if defined(CONFIG_IDF_TARGET_ESP32P4)`, so it compiles on every P4 host
whether or not `espnow` is configured, and it includes `<esp_now.h>`. That
header is provided by the built-in IDF `esp_wifi` component, which is listed in
`DEFAULT_EXCLUDED_IDF_COMPONENTS` in `esphome/components/esp32/__init__.py` and
so is filtered out of the `REQUIRES` list generated for `src`.

`esp32_hosted`'s `to_code()` enables the shim for every P4 host
(`add_define("USE_ESP_NOW_HOSTED")`, the two CustomRpc sdkconfig options) but
never calls `include_builtin_idf_component("esp_wifi")` to match.

The build therefore only succeeds when some unrelated component happens to
re-include `esp_wifi`:

- `wifi` -> `request_wifi()` -> `include_builtin_idf_component("esp_wifi")`
- `espnow` -> calls `include_builtin_idf_component("esp_wifi")` directly
- any BLE component -> `request_bluetooth()` -> includes `bt`, whose own
  REQUIRES pulls `esp_wifi` in transitively

This matches the existing comment on the `esp_wifi` entry in that list
("re-included by request_wifi(), espnow; bt pulls it back for BLE builds") --
`esp32_hosted` is a fourth consumer that was not added to it.

Across my 13 ESP32-P4 devices, 5 failed and 8 built fine. The 8 that built only
did so because they had `wifi:` or `bluetooth_proxy:`. Two devices share an
identical Ethernet base config and differ only in that one does
`bluetooth_proxy: !remove` -- that one fails and the other succeeds, which
isolates the dependency cleanly.

The identical file builds on 2026.8.2 (`Successfully compiled program`, flash
29.3%), where `esp_now_hosted.cpp` did not yet exist, and fails on 2026.9.0. So
this is a regression in 2026.9.0, not a pre-existing config problem.

### Which version of ESPHome has the issue?

2026.9.0

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Component causing the issue

esp32_hosted

### YAML Config

```yaml
esphome:
  name: p4-espnow-repro

esp32:
  board: esp32-p4-evboard
  framework:
    type: esp-idf

esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  active_high: true
  clk_pin: GPIO18
  cmd_pin: GPIO19
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17

logger:


That is the complete file -- no `wifi:`, no `ethernet:`, no BLE, no `espnow`.
Compiling it with 2026.9.0 fails; the same file on 2026.8.2 builds.
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2026.9.0
INFO Compiling app... Build path: .esphome/build/p4-espnow-repro
...
[954/997] Building CXX object esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/esp32_hosted/esp_now_hosted.cpp.obj
FAILED: esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/esp32_hosted/esp_now_hosted.cpp.obj
../src/esphome/components/esp32_hosted/esp_now_hosted.cpp:33:10: fatal error: esp_now.h: No such file or directory
   33 | #include <esp_now.h>         // injected declarations we are now DEFINING
      |          ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Compilation failed because esp_now_hosted.cpp (in "src" component) includes esp_now.h, provided by esp_wifi component(s).
However, esp_wifi component(s) is not in the requirements list of "src".
To fix this, add esp_wifi to PRIV_REQUIRES list of idf_component_register call in .esphome/build/p4-espnow-repro/src/CMakeLists.txt.
ninja failed with exit code 1
```

### Workaround

There is a workaround for this issue, re-including the component from YAML is enough:

    esp32:
      framework:
        type: esp-idf
        advanced:
          include_builtin_idf_components: [esp_wifi]

This only restores header visibility -- it does not enable Wi-Fi. Building the
minimal config above with and without that option on 2026.9.0 produces a
byte-identical `sdkconfig.h`:

    without (fails):  60175 bytes  md5 8837d2a65c379f150e460a8b5f13b90b
    with    (builds): 60175 bytes  md5 8837d2a65c379f150e460a8b5f13b90b

`CONFIG_ESP_WIFI_ENABLED` and `CONFIG_SOC_WIFI_SUPPORTED` are undefined in
both; `CONFIG_ESP_WIFI_REMOTE_ENABLED` is set in both, by `esp32_hosted`. The
resulting `libesp_wifi.a` is 1424 bytes and contains only `dummy_src.c.obj` --
the P4 has no Wi-Fi radio, so the built-in component compiles to a stub.

Also verified on two real devices (one Ethernet + BLE, one Ethernet without).

### Suggested fix

In `esphome/components/esp32_hosted/__init__.py`, in the P4 branch of
`to_code()` that already enables the shim:

    if esp32.get_esp32_variant() == esp32.VARIANT_ESP32P4:
        add_define("USE_ESP_NOW_HOSTED")
        # esp_now_hosted.cpp includes <esp_now.h>, provided by the built-in
        # esp_wifi component, which is excluded by default.
        esp32.include_builtin_idf_component("esp_wifi")
        ...

That matches how `espnow` and `wifi` already declare the same dependency.

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

On the ESP32-P4, `esp32_hosted` always builds `esp_now_hosted.cpp`, which includes `esp_now.h` from the IDF `esp_wifi` component. That component is excluded by default, so the build only worked when `wifi`, `espnow` or a Bluetooth component happened to pull it back in. A P4 with `esp32_hosted` and only ethernet failed with `esp_now.h: No such file or directory`.

`esp32_hosted` now adds `esp_wifi` back itself on the P4, the same way `espnow` does. The P4 has no radio, so this only makes the header visible; `esp_wifi` still builds as an empty stub.

Added a test config with no `wifi:` block, since every existing `esp32_hosted` test had one, which is why CI missed this. It fails on `dev` and builds with this change.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New developer-facing feature (adds functionality for component developers; no end-user configuration change)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) — [policy](https://developers.esphome.io/contributing/code/#what-constitutes-a-c-breaking-change)
- [ ] Developer breaking change (an API change that could break external components) — [policy](https://developers.esphome.io/contributing/code/#what-is-considered-public-c-api)
- [ ] Undocumented C++ API change (removal or change of undocumented public methods that lambda users may depend on) — [policy](https://developers.esphome.io/contributing/code/#c-user-expectations)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/esphome/issues/19341

**Pull request in [esphome.io](https://github.com/esphome/esphome.io) with documentation (if applicable):**

- esphome/esphome.io#<esphome.io PR number goes here>

**Pull request in [developers.esphome.io](https://github.com/esphome/developers.esphome.io) with developer documentation (if applicable):**

- esphome/developers.esphome.io#<developers.esphome.io PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040/RP2350
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esp32:
  board: esp32-p4-evboard
  framework:
    type: esp-idf

esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  active_high: true
  clk_pin: GPIO18
  cmd_pin: GPIO19
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome.io](https://github.com/esphome/esphome.io).

### CODE REVIEW

**Comment by bdraco** [comment]
@bluetoothbot review

**Review by swoboda1337 — APPROVED** [review]

**Review by bluetoothbot — APPROVED** [review]
> [!TIP]
> No blocking issues found — ready to merge.

**Comment by bdraco** [comment]
thanks
