### PR TITLE
[remote_base] Make protocol methods non-virtual and size receiver lists from codegen

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

`RemoteProtocol<T>` declared `encode`, `decode` and `dump` as virtual, but every caller (transmit actions, dumpers, triggers, binary sensors) goes through the concrete protocol type, so the vtable kept all three bodies of every instantiated protocol in the image. The CI memory report on this PR measured 14.6 KB less flash on the ESP8266 test build with a receiver and the ir_rf_proxy platforms, and 11.9 KB less on the ESP32 IDF build that also carries the four climate components.

What changed:

- `encode`, `decode` and `dump` are plain members; the linker drops whichever side a configuration does not use. Concepts (`RemoteProtocolDecoder`, `RemoteProtocolDumper`, `RemoteProtocolEncoder`) constrain the consuming templates, so a protocol missing a method fails at its own header.
- The receiver's listener and dumper lists are `StaticVector`s sized by `cg.slot_counter()` keyed per receiver; a receiver with no dumpers or no listeners compiles that path out. infrared and ir_rf_proxy register from codegen instead of `setup()`, and the single secondary dumper (raw) is one pointer.
- Only the protocol source files a configuration uses are compiled: dumpers, triggers, binary sensors and transmit actions record their protocol with `remote_base.request_protocol()`, the four climate components that use one from C++ request theirs in `to_code()`, and `dump: all` keeps everything.
- `RC_SWITCH_PROTOCOLS` is a constexpr table in flash (`PROGMEM`, its `bool` widened to a word for ESP8266) instead of a global constructor filling bss. A dumper listed twice in `dump:` is deduplicated at validation, and a bare receiver has its own compile fixture.

Why a clean break: every protocol added to remote_base has cost every user of the component, whether their configuration used it or not, since each vtable and every `encode()`, `decode()` and `dump()` body stayed in the image. There are 35 protocols in tree and more arrive most releases, so the tax kept growing for users who need one or two. There is no way to keep `override` compiling on a method that is no longer virtual, so a deprecation window is not possible.

## Migration for external components

The full guide, including how to support 2026.9 and 2026.10 at the same time, is the blog post in esphome/developers.esphome.io#177. Summary:

- Protocol classes drop `override` from `encode`, `decode` and `dump`.
- Listeners and dumpers register from `to_code()` with `remote_base.attach_receiver()`, `register_listener()`, `add_listener()` or `add_dumper()`; a C++ registration fails the build.
- A protocol used from C++ or a lambda needs `remote_base.request_protocol("<name>")` or a reference elsewhere in the configuration.
- Receiver platforms call `call_listeners_dumpers_()` instead of the two halves.

<details>
<summary>Migration guide with before and after examples</summary>

#### Protocol classes

Classes deriving from `RemoteProtocol<T>` must drop `override` from `encode`, `decode` and `dump`. The methods are no longer virtual, so the compiler reports each one:

```cpp
// before
class MyProtocol : public RemoteProtocol<MyData> {
 public:
  void encode(RemoteTransmitData *dst, const MyData &data) override;
  optional<MyData> decode(RemoteReceiveData src) override;
  void dump(const MyData &data) override;
};

// after
class MyProtocol : public RemoteProtocol<MyData> {
 public:
  void encode(RemoteTransmitData *dst, const MyData &data);
  optional<MyData> decode(RemoteReceiveData src);
  void dump(const MyData &data);
};
```

The signatures themselves are unchanged and are now checked by the `RemoteProtocolDecoder`, `RemoteProtocolDumper` and `RemoteProtocolEncoder` concepts wherever the protocol is used, so a mismatch is reported at the `DECLARE_REMOTE_PROTOCOL(...)` line, normally in the protocol's own header; a protocol declared without that macro sees it at its first use.

#### Listeners and dumpers

The receiver's listener and dumper lists are sized at code generation. A component that registered itself from C++ no longer has a slot:

```cpp
// before, in setup()
this->receiver_->register_listener(this);
```

Register from Python instead, so the slot is counted:

```python
# after, in to_code()
receiver = await cg.get_variable(config[CONF_RECEIVER_ID])
cg.add(var.set_receiver(receiver))
remote_base.add_listener(receiver, var)
```

`remote_base.attach_receiver(var, config, key=CONF_RECEIVER_ID)` does both halves, `set_receiver` and the counted registration, for any entity with a receiver option; `remote_base.register_listener(var, config)` still works for components whose schema uses `CONF_RECEIVER_ID`. Dumpers use `remote_base.add_dumper(receiver, dumper)`.

A receiver platform deriving from `RemoteReceiverBase` that called the protected `call_listeners_()` and `call_dumpers_()` separately now calls `call_listeners_dumpers_()`, which already existed as the combined entry point; the two halves were merged so each list can compile out on its own.

#### Protocols used from C++

A component that uses a protocol class directly in C++ (without a dumper, trigger, binary sensor or transmit action for it in the configuration) must keep its source file in the build:

```python
# in to_code()
remote_base.request_protocol("coolix")
```

Otherwise the protocol's `.cpp` is filtered out and the link fails with an undefined reference to its `encode`, `decode` or `dump`.

The same applies to a YAML lambda that uses a protocol class directly, for example `id(tx).transmit<remote_base::NECProtocol>(data)`. The config has to reference that protocol somewhere else so its source stays in the build: a `dump` entry, an `on_nec` trigger or a `remote_transmitter.transmit_nec` action.

A registration from C++ now fails loudly instead of being dropped silently: when no slot was counted at all the build stops on a `static_assert` naming this fix, and when the counted slots are already used the same message is logged at runtime.

Every receiver's list has the same capacity, so the define is the largest count any single receiver needs; a second receiver with a shorter dumper list carries the difference as unused pointer slots. This is static storage that replaces the heap allocation the `std::vector` made at setup.

#### Supporting multiple ESPHome versions

`override` on a method that is no longer virtual is a compile error, so a component that has to build on 2026.9 and 2026.10 needs a version guard around the declarations:

```cpp
#include "esphome/core/version.h"

class MyProtocol : public RemoteProtocol<MyData> {
 public:
#if ESPHOME_VERSION_CODE >= VERSION_CODE(2026, 10, 0)
  void encode(RemoteTransmitData *dst, const MyData &data);
  optional<MyData> decode(RemoteReceiveData src);
  void dump(const MyData &data);
#else
  void encode(RemoteTransmitData *dst, const MyData &data) override;
  optional<MyData> decode(RemoteReceiveData src) override;
  void dump(const MyData &data) override;
#endif
};
```

For listeners, `remote_base.register_listener(var, config)` exists on both versions, so a component whose schema uses `CONF_RECEIVER_ID` can move the registration to Python once and drop the C++ call with no guard. A component that keeps its own receiver option needs `add_listener`, which only exists from 2026.10.0; keep the C++ registration for older versions:

```python
# in to_code()
receiver = await cg.get_variable(config[CONF_RECEIVER_ID])
cg.add(var.set_receiver(receiver))
try:
    from esphome.components.remote_base import add_listener
except ImportError:
    pass  # ESPHome < 2026.10.0 registers from setup()
else:
    add_listener(receiver, var)
```

```cpp
void MyComponent::setup() {
#if ESPHOME_VERSION_CODE < VERSION_CODE(2026, 10, 0)
  this->receiver_->register_listener(this);
#endif
}
```

`request_protocol` follows the same shape; before 2026.10.0 every protocol source file is compiled, so the import failing is fine to ignore.

</details>

<details>
<summary>Known external components affected</summary>

Found by a GitHub code search, excluding forks and vendored copies of esphome.

Protocol classes with `override` (compile error until removed):

- [pauln/esphome-linp-doorbell-g04](https://github.com/pauln/esphome-linp-doorbell-g04) (`linptech_g6l_protocol.h`, `szy8039b_protocol.h`)
- [brown-studios/esphome-maxxfan-protocol](https://github.com/brown-studios/esphome-maxxfan-protocol) (`maxxfan_protocol.h`)
- [alexyao2015/ESPHomeYAML](https://github.com/alexyao2015/ESPHomeYAML) (`custom_ir_protocols/*_protocol.h`, four protocols)
- [kitsuned/esphome-configs](https://github.com/kitsuned/esphome-configs) (`rapid/rapid_protocol.h`)
- [pputerla/esphome-custom-components](https://github.com/pputerla/esphome-custom-components) (`remote_receiver_tcl/tcl_protocol.h`)
- [Weissnix4711/esphome-opentherm-custom](https://github.com/Weissnix4711/esphome-opentherm-custom) (`opentherm/opentherm_protocol.h`)

Listeners or dumpers registered from C++ `setup()` (build error, no slot):

- [AzonInc/Doorman](https://github.com/AzonInc/Doorman) (`tc_bus`)
- [maciekczwa/esphome_alecto](https://github.com/maciekczwa/esphome_alecto) (`alecto_receiver.h`)
- [leonardpitzu/esphome_somfy](https://github.com/leonardpitzu/esphome_somfy) (`somfy_hub_rts`)
- [swoboda1337/somfy-esphome](https://github.com/swoboda1337/somfy-esphome) (`somfy`)
- [CoMPaTech/esphome_ct](https://github.com/CoMPaTech/esphome_ct) (`ithofan`)
- [berfenger/esphome-mantra-rf-433](https://github.com/berfenger/esphome-mantra-rf-433) (`mantra_rf_433/bridge`)
- [ryanh7/esphome-custom-components](https://github.com/ryanh7/esphome-custom-components) (`rf_bridge_cc1101`, wraps both `register_listener` and `register_dumper`)

</details>

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New developer-facing feature (adds functionality for component developers; no end-user configuration change)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) — [policy](https://developers.esphome.io/contributing/code/#what-constitutes-a-c-breaking-change)
- [x] Developer breaking change (an API change that could break external components) — [policy](https://developers.esphome.io/contributing/code/#what-is-considered-public-c-api)
- [x] Undocumented C++ API change (removal or change of undocumented public methods that lambda users may depend on) — [policy](https://developers.esphome.io/contributing/code/#c-user-expectations)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- related to https://github.com/esphome/esphome/issues/19033

**Pull request in [esphome.io](https://github.com/esphome/esphome.io) with documentation (if applicable):**

- esphome/esphome.io#<esphome.io PR number goes here>

**Pull request in [developers.esphome.io](https://github.com/esphome/developers.esphome.io) with developer documentation (if applicable):**

- esphome/developers.esphome.io#177

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [ ] RP2040/RP2350
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
remote_receiver:
  - pin: GPIO4
    dump: all
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome.io](https://github.com/esphome/esphome.io).

### CODE REVIEW

**Review by bluetoothbot — APPROVED** [review]
> [!TIP]
> No blocking issues found — ready to merge.

**Review by kbx81 — DISMISSED** [review]
Working on my C6 board here -- nice size reduction:
```
Total image size: 945614 bytes (.bin may be padded larger)
RAM:   [===       ]  33.6% (used 152104 bytes from 452112 bytes)
Flash: [=====     ]  51.5% (used 945614 bytes from 1835008 bytes)
```
...vs....
```
Total image size: 944454 bytes (.bin may be padded larger)
RAM:   [===       ]  33.6% (used 152088 bytes from 452112 bytes)
Flash: [=====     ]  51.5% (used 944454 bytes from 1835008 bytes)
```

**Review by bluetoothbot — CHANGES_REQUESTED** [review]
> [!WARNING]
> Important issues found.
>
> - Dumper dedupe raises TypeError on a non-str, non-dict list item

**Review by bluetoothbot — APPROVED** [review]
> [!TIP]
> No blocking issues found — ready to merge.

**Review by bluetoothbot — APPROVED** [review]
> [!TIP]
> No blocking issues found — ready to merge.

**Review by bluetoothbot — APPROVED** [review]
> [!TIP]
> No blocking issues found — ready to merge.

**Comment by bdraco** [comment]
@esphbot review

**Comment by bdraco** [comment]
@esphbot review

**Review by bluetoothbot — APPROVED** [review]
> [!TIP]
> No blocking issues found — ready to merge.

**Review by bluetoothbot — APPROVED** [review]
> [!TIP]
> No blocking issues found — ready to merge.

**Review by bluetoothbot — APPROVED** [review]
> [!TIP]
> No blocking issues found — ready to merge.

**Review by kbx81 — APPROVED** [review]
Thanks! 🚀
