### PR TITLE
[esp32_ble] Add mac filtering

### PR DESCRIPTION
**Pull request by shajen**
# What does this implement/fix?

This pull request introduces a BLE MAC address whitelist mechanism for the ESP32 module.

The new functionality adds a configurable list of allowed MAC addresses that controls two aspects of BLE communication:

- Connection filtering – only devices whose MAC addresses are present in the whitelist can establish a connection with the ESP32 board.

- Advertisement filtering – during scanning, the ESP32 processes advertisement packets exclusively from whitelisted devices, ignoring all others.

This enhancement improves security by restricting access to explicitly authorized devices and reduces unnecessary processing by filtering out irrelevant BLE traffic at an early stage.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) — [policy](https://developers.esphome.io/contributing/code/#what-constitutes-a-c-breaking-change)
- [ ] Developer breaking change (an API change that could break external components) — [policy](https://developers.esphome.io/contributing/code/#what-is-considered-public-c-api)
- [ ] Undocumented C++ API change (removal or change of undocumented public methods that lambda users may depend on) — [policy](https://developers.esphome.io/contributing/code/#c-user-expectations)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- https://github.com/esphome/feature-requests/issues/2686

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- https://github.com/esphome/esphome-docs/pull/6169

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] LN882x
- [ ] nRF52840

## Example entry for `config.yaml`:

```yaml
esphome:
  name: test

esp32:
  variant: esp32

esp32_ble:
  filter:
    mac_address:
      - value: 00:11:22:33:44:55
      - value: 00:11:22:33:44:56
      - value: 00:11:22:33:44:57
      - value: 00:11:22:33:44:58
        public: true
      - value: 00:11:22:33:44:59
        public: false

esp32_ble_tracker:
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by bdraco** [comment]
See previous attempts and review comments on those
#6752  #7216

This is a better approach of putting filtering at the esp32_ble level using the ESP-IDF hardware whitelist API

File: esphome/components/esp32_ble/ble.h [hunk 1]
```diff
@@ -124,6 +125,10 @@ class ESP32BLE : public Component {
   }
   uint32_t get_advertising_cycle_time() const { return this->advertising_cycle_time_; }
 
+  void set_allowed_addresses(const std::initializer_list<uint64_t> &allowed_addresses) {
+    allowed_addresses_ = allowed_addresses;
```
Comment (bdraco) [inline esphome/components/esp32_ble/ble.h]:
```suggestion
    this->allowed_addresses_ = allowed_addresses;
```

https://developers.esphome.io/contributing/code/#c-code-style

File: esphome/components/esp32_ble/ble.cpp [hunk 2]
```diff
@@ -329,6 +330,28 @@ bool ESP32BLE::ble_setup_() {
...
+      return false;
+    }
+
+    for (const uint64_t &mac : this->allowed_addresses_) {
+      esp_bd_addr_t esp_address;
+      esp32_ble::uint64_to_ble_addr(mac, esp_address);
+      char mac_buf[MAC_ADDRESS_PRETTY_BUFFER_SIZE];
+      format_mac_addr_upper(esp_address, mac_buf);
+      ESP_LOGD(TAG, "add to allowed addresses list: %s", mac_buf);
+      err = esp_ble_gap_update_whitelist(true, esp_address, BLE_WL_ADDR_TYPE_PUBLIC);  // NOLINT(inclusive-language)
```
Comment (bdraco) [inline esphome/components/esp32_ble/ble.cpp]: see the comments on #6752 about user confusion with random macs

File: esphome/components/esp32_ble/ble_advertising.cpp [hunk 3]
```diff
@@ -33,7 +34,8 @@ BLEAdvertising::BLEAdvertising(uint32_t advertising_cycle_time) : advertising_cy
   this->advertising_params_.adv_type = ADV_TYPE_IND;
   this->advertising_params_.own_addr_type = BLE_ADDR_TYPE_PUBLIC;
   this->advertising_params_.channel_map = ADV_CHNL_ALL;
-  this->advertising_params_.adv_filter_policy = ADV_FILTER_ALLOW_SCAN_ANY_CON_ANY;
+  this->advertising_params_.adv_filter_policy =
+      allowed_addresses_is_empty ? ADV_FILTER_ALLOW_SCAN_ANY_CON_ANY : ADV_FILTER_ALLOW_SCAN_WLST_CON_WLST;
```
Comment (bdraco) [inline esphome/components/esp32_ble/ble_advertising.cpp]: ADV_FILTER_ALLOW_SCAN_WLST_CON_WLST is very aggressive this restricts both scanning AND incoming connections to whitelisted addresses and will likely break quite a few things including improv provisioning.  I would make these separate PRs and separate options.  The adv filtering is the high value so it should be in the first pr.

File: esphome/components/esp32_ble/ble_advertising.h [hunk 4]
```diff
@@ -19,7 +19,7 @@ class ESPBTUUID;
 
 class BLEAdvertising {
  public:
-  BLEAdvertising(uint32_t advertising_cycle_time);
+  BLEAdvertising(uint32_t advertising_cycle_time, bool allowed_addresses_is_empty);
```
Comment (bdraco) [inline esphome/components/esp32_ble/ble_advertising.h]: allowed_addresses_is_empty is a double-negative semantic. Better to pass the filter policy directly or a  bool use_allowlist.

File: esphome/components/esp32_ble/__init__.py [hunk 5]
```diff
@@ -595,6 +604,10 @@ async def to_code(config):
         cg.add_define("USE_ESP32_BLE_ADVERTISING")
         cg.add_define("USE_ESP32_BLE_UUID")
 
+    if config[CONF_FILTER] and config[CONF_FILTER][CONF_MAC_ADDRESS]:
+        allowed_addresses = [it.as_hex for it in config[CONF_FILTER][CONF_MAC_ADDRESS]]
+        cg.add(var.set_allowed_addresses(allowed_addresses))
```
Comment (bdraco) [inline esphome/components/esp32_ble/__init__.py]: config[CONF_FILTER][CONF_MAC_ADDRESS] is optional without a default. needs .get()

File: esphome/components/esp32_ble/ble.h [hunk 6]
```diff
@@ -213,6 +218,7 @@ class ESP32BLE : public Component {
   // Large objects (size depends on template parameters, but typically aligned to 4 bytes)
   esphome::LockFreeQueue<BLEEvent, MAX_BLE_QUEUE_SIZE> ble_events_;
   esphome::EventPool<BLEEvent, MAX_BLE_QUEUE_SIZE> ble_event_pool_;
+  std::vector<uint64_t> allowed_addresses_;
```
Comment (bdraco) [inline esphome/components/esp32_ble/ble.h]: the size is known at compile time. we don't need dynamic allocation. use std::array or StaticVector

File: esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp [hunk 7]
```diff
@@ -247,9 +247,14 @@ void ESP32BLETracker::start_scan_(bool first) {
 #ifdef USE_ESP32_BLE_DEVICE
   this->already_discovered_.clear();
 #endif
+  uint16_t list_size = 0;
+  esp_err_t err = esp_ble_gap_get_whitelist_size(&list_size);  // NOLINT(inclusive-language)
+  if (err != ESP_OK) {
+    ESP_LOGE(TAG, "esp_ble_gap_get_whitelist_size failed: %d", err);  // NOLINT(inclusive-language)
+  }
```
Comment (bdraco) [inline esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp]: shouldn't be querying the whitelist size at runtime every scan cycle. esp32_ble already knows

**Comment by bdraco** [comment]
We should gate the whole feature with ifdefs since very few people need this

**Review by bdraco — CHANGES_REQUESTED** [review]
Thanks for putting this together! This is the right approach, putting the filtering at the esp32_ble level using the hardware whitelist API is much better than the previous attempts in #6752 and #7216 which tried to do it higher up in the stack. The memory impact is reasonable too.

There are a few things that need to be addressed before this can be merged:

1. Missing this-> prefix in set_allowed_addresses. All member access needs the this-> prefix per the style guide.

2. The random MAC address problem. See the comments on #6752 where users ran into confusion because many BLE devices (phones, smartwatches, lots of sensors) use random addresses, not public ones. Right now BLE_WL_ADDR_TYPE_PUBLIC is hardcoded which means this filter silently wont work for those devices. This needs to be thought through, at minimum documented, but ideally the address type should be configurable or auto detected.

3. ADV_FILTER_ALLOW_SCAN_WLST_CON_WLST restricts both scan responses and incoming connections to whitelisted devices. That is very aggressive and will break things like improv provisioning for anyone not in the whitelist. The advertisement filtering is the high value feature here. I would split this into two separate PRs with separate config options. Get the scan/advertisement filtering in first, then follow up with connection filtering as its own option.

4. The allowed_addresses_is_empty parameter passed to BLEAdvertising is a double negative semantic. Pass the filter policy directly or a bool use_allowlist instead.

5. In the Python config, config[CONF_FILTER][CONF_MAC_ADDRESS] will KeyError if someone specifies filter: without mac_address since its Optional without a default. Needs a .get() call.

6. The std::vector<uint64_t> for allowed_addresses_ should be std::array or StaticVector since the size is known at compile time from the YAML config. No need for dynamic allocation here.

7. In esp32_ble_tracker, the code queries esp_ble_gap_get_whitelist_size every scan cycle to decide the filter policy. The esp32_ble component already knows whether filtering is enabled from configuration, so the tracker should get that information from esp32_ble (via a setter during codegen or a getter) rather than probing the BLE stack at runtime.

8. The whole feature should be guarded behind ifdefs (add a define like USE_ESP32_BLE_ALLOWLIST via cg.add_define and wrap the whitelist code in #ifdef blocks). Very few users will need this and without the guards the whitelist setup code, the address list, and the extra logic in ble_setup_ and start_scan_ all get compiled into every build even when no filter is configured.

The suggested next steps would be to fix items 1, 4, 5, 6, 7, and 8 in this PR, scope this PR to advertisement/scan filtering only (removing the connection filter changes from ble_advertising.cpp), and then open a follow up PR for connection filtering as a separate config option.

**Comment by shajen** [comment]
Thanks for the feedback - I’ve incorporated all of it in the latest changes!

**Comment by mtheli** [comment]
Thanks for working on this — the hardware-whitelist approach is exactly right for single-purpose bridges (e.g. one ESP dedicated to one BLE device).

I'd like to raise a use case that this PR doesn't cover, in case it's worth scoping a complementary option:

**Multi-proxy bonding conflicts.** When several `bluetooth_proxy` nodes are deployed across a house and one of the BLE devices requires bonding (e.g. a Philips Sonicare Prestige 9900), every proxy in range tries to handle that device. Only one can hold the bond cleanly; the others cause connection thrashing and (until ESPHome 2026.2) intermittent Bluedroid crashes.

A whitelist solves this only awkwardly:
- Whitelisting just the bonded device on one proxy turns that proxy into a single-purpose bridge — it can no longer relay anything else.
- Whitelisting "everything except the bonded device" on the other proxies means maintaining the full BLE inventory in N YAMLs.

What would actually fit is a **deny / blacklist** counterpart to this whitelist — "this proxy ignores these MACs, everything else proceeds normally". Same schema, same `filter:` block, just an additional `deny:` (or `block:`) list. There's no hardware controller mode for it, so it would have to be a software check in the GAP scan-result and connect paths, but the cost per ADV packet is a `memcmp` against a small list.

This matches an existing — though largely unnoticed — feature request: [esphome/feature-requests#2908](https://github.com/esphome/feature-requests/issues/2908) "Bind / Whitelist / Blacklist Devices to specific Proxy".

Two questions:
1. Would you / @bdraco be open in principle to a `deny:` block alongside `mac_address:` in the same `filter:` config, as a follow-up PR after this one merges?
2. If yes, should it live in `esp32_ble` next to the whitelist code, or rather in `bluetooth_proxy` (since that's where the use case actually surfaces)?

Happy to take that on once this lands — just want to check the direction is welcome before writing code.

**Comment by Schonhoffer** [comment]
This is working great for me, solves my problem of multiple Bluetooth proxies all thrashing and unreliable connections to anything. The yaml syntax is now different than original PR description, so sharing my example:

```yaml
external_components:
  - source: github://pr#14353
    components: [bluetooth_proxy, esp32_ble, esp32_ble_tracker]
    refresh: 1h

esp32_ble:
  filter:
    mac_address:
      - value: "DE:AD:BE:EF:00:00"
      - value: "DE:AD:BE:EF:11:11"

bluetooth_proxy:
  active: true
  connection_slots: 2
```

**Comment by RikyUnreal** [comment]
I'm also waiting for this feature.
Thank you!

File: esphome/components/esp32_ble/ble.cpp [hunk 8]
```diff
@@ -325,6 +325,32 @@ bool ESP32BLE::ble_setup_() {
...
+    for (const allowlist_item_t &allowlist_item : this->allowlist_items_) {
+      esp_bd_addr_t esp_address;
+      esp32_ble::uint64_to_ble_addr(allowlist_item.mac_address, esp_address);
+      char mac_buf[MAC_ADDRESS_PRETTY_BUFFER_SIZE];
+      format_mac_addr_upper(esp_address, mac_buf);
+      ESP_LOGD(TAG, "add to allowlist, mac address: %s, is public: %s", mac_buf,
+               allowlist_item.is_public ? "true" : "false");
+      err = esp_ble_gap_update_whitelist(true, esp_address,  // NOLINT(inclusive-language)
+                                         allowlist_item.is_public ? BLE_WL_ADDR_TYPE_PUBLIC : BLE_WL_ADDR_TYPE_RANDOM);
+      if (err != ESP_OK) {
```
[the remark this answers is not in the document]
Comment (shajen) [reply esphome/components/esp32_ble/ble.cpp:384]: This was added in the initial version of MR, but at @bdraco suggestion it was removed as too aggressive - for future consideration.

**Comment by davidcoulson** [comment]
Is there an approach where the filter could take a wild card? I have a number of BLE devices where I can change the MAC address, so it's easier just to filter XX:XX:XX:XX::XX:?? vs adding them all in manually.

**Comment by davidcoulson** [comment]
> This is working great for me, solves my problem of multiple Bluetooth proxies all thrashing and unreliable connections to anything. The yaml syntax is now different than original PR description, so sharing my example:
> 
> ```yaml
> external_components:
>   - source: github://pr#14353
>     components: [bluetooth_proxy, esp32_ble, esp32_ble_tracker]
>     refresh: 1h
> 
> esp32_ble:
>   filter:
>     mac_address:
>       - value: "DE:AD:BE:EF:00:00"
>       - value: "DE:AD:BE:EF:11:11"
> 
> bluetooth_proxy:
>   active: true
>   connection_slots: 2
> ```

Is this syntax correct for PR14353? I tried it on my 50+ BLE proxies and it basically filtered out everything. Obviously I replaced the MAC addresses with devices I know are BLE beacons with static MAC addresses (no IRK stuff).

**Comment by davidcoulson** [comment]
FYI this PR doesn't seem to build with 2026.5.1 - Seemed to build ok with 2026.5.0 atlhough not sure it functioned correectly.

```

[21/103] Building CXX object esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp.obj
FAILED: esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp.obj
/data/idf/tools/xtensa-esp-elf/esp-15.2.0_20251204/xtensa-esp-elf/bin/xtensa-esp32s3-elf-g++ @esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp.obj.rsp -MD -MT esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp.obj -MF esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp.obj.d -o esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp.obj -c /data/build/ble-esp32-eth-f7a3fc/src/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp
/data/build/ble-esp32-eth-f7a3fc/src/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp: In member function 'virtual bool esphome::bluetooth_proxy::BluetoothProxy::parse_devices(const esphome::esp32_ble::BLEScanResult*, size_t)':
/data/build/ble-esp32-eth-f7a3fc/src/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp:80:13: error: 'global_api_server' is not a member of 'esphome::api'
   80 |   if (!api::global_api_server->is_connected() || this->api_connection_ == nullptr)
      |             ^~~~~~~~~~~~~~~~~
/data/build/ble-esp32-eth-f7a3fc/src/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp: In member function 'virtual void esphome::bluetooth_proxy::BluetoothProxy::loop()':
/data/build/ble-esp32-eth-f7a3fc/src/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp:130:12: error: 'global_api_server' is not a member of 'esphome::api'
  130 |   if (api::global_api_server->is_connected() && this->api_connection_ != nullptr) {
      |            ^~~~~~~~~~~~~~~~~
[30/103] Building CXX object esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/esphome/ota/ota_esphome.cpp.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the /data/build/ble-esp32-eth-f7a3fc/build/log/idf_py_stderr_output_505734 and /data/build/ble-esp32-eth-f7a3fc/build/log/idf_py_stdout_output_505734
```

**Comment by shajen** [comment]
> Is there an approach where the filter could take a wild card? I have a number of BLE devices where I can change the MAC address, so it's easier just to filter XX:XX:XX:XX::XX:?? vs adding them all in manually.

No. `esp32` do not support wildcard in whitelisting `ble`.

> > This is working great for me, solves my problem of multiple Bluetooth proxies all thrashing and unreliable connections to anything. The yaml syntax is now different than original PR description, so sharing my example:
> > ```yaml
> > external_components:
> >   - source: github://pr#14353
> >     components: [bluetooth_proxy, esp32_ble, esp32_ble_tracker]
> >     refresh: 1h
> > 
> > esp32_ble:
> >   filter:
> >     mac_address:
> >       - value: "DE:AD:BE:EF:00:00"
> >       - value: "DE:AD:BE:EF:11:11"
> > 
> > bluetooth_proxy:
> >   active: true
> >   connection_slots: 2
> > ```
> 
> Is this syntax correct for PR14353? I tried it on my 50+ BLE proxies and it basically filtered out everything. Obviously I replaced the MAC addresses with devices I know are BLE beacons with static MAC addresses (no IRK stuff).

The syntax is ok, but this configuration rejects all bluetooth devices except the given MAC addresses.



> FYI this PR doesn't seem to build with 2026.5.1 - Seemed to build ok with 2026.5.0 atlhough not sure it functioned correectly.

Check again now.

**Comment by gitflo7123** [comment]
Hi guys, It's been mentioned earlier, but I believe this would be much better with the option of deny or blacklist listed MACs. 

For example, there is a bug with receiving advertisements from H5074 sensors by ESP32s, and I need them to be picked up by the main BT dongle only. Only a deny MAC at the ESP32 individually would work here, there are other use cases also of course.

Thanks.

**Comment by davidcoulson** [comment]
> > FYI this PR doesn't seem to build with 2026.5.1 - Seemed to build ok with 2026.5.0 atlhough not sure it functioned correectly.
> 
> Check again now.

Awesome works now - I just need to figure out how i'm going to deal with my IRK sensors.

is there a similar PR that adds rssi filtering to the esp32_ble component - For example, if anything has a RSSI >75dBm just drop it similar to how the mac whitelist works?

**Comment by freshfieldx** [comment]
This PR is a gamechanger, my BT proxy Esp32s can finally cope and my remote devices are not spamming the network with mac address activity. I'm really surprised more people are not behind this? Thanks for getting it this far.

**Comment by dseven** [comment]
Just came across this PR while looking for a way to control which proxies get used for my devices in a multi-room environment.

As others have said, blacklisting probably would work better for me, but I could live with whitelisting. That said, I think maybe it would be prudent to name the config key something like "allowed_mac_addresses", which would both make the purpose clear and  leave the door open for potential blacklisting in the future.

It might be nice to add a ESP_LOGCONFIG() to show the configured filter(s).

That aside, I seem to be having difficulty getting this to work, or maybe I'm misunderstanding what it's supposed to do. I've added config like the posts above, and (when viewing logging over serial, but not over network - must be too early - ugh) I see the corresponding "add to allowlist, mac address:" debug messages, but it seems to filter out everything, including the four devices whose MAC addresses I've included - in that Home Assistant no longer sees any advertisements from that proxy, and the devices that are not in range of another proxy eventually fall off the map.

Update: turns out that I didn't understand the "public" address concept well enough. Specifying "public: false" seems to make it work as I expect (or at least I see (only) the advertisements that I expect now).

File: esphome/components/esp32_ble/__init__.py [hunk 9]
```diff
@@ -346,6 +350,18 @@ def register_bt_logger(*loggers: BTLoggers) -> None:
...
         ),
+        cv.Optional(CONF_FILTER, default={}): cv.All(
+            cv.Schema(
+                {
+                    cv.Optional(CONF_MAC_ADDRESS, default=[]): cv.ensure_list(
+                        {
+                            cv.Required(CONF_VALUE): cv.mac_address,
+                            cv.Optional(CONF_PUBLIC, default=True): cv.boolean,
+                        }
+                    ),
```
Comment (Unfocused) [inline esphome/components/esp32_ble/__init__.py:366]: It would help in terms of usability to allow each item in the `filter.mac_address` list to be either this Dict or just a `cv.mac_address`. So the YAML syntax could be:


```yaml
esp32_ble:
  filter:
    mac_address:
      - 00:11:22:33:44:55
      - 00:11:22:33:44:56
      - value: 00:11:22:33:44:57
      - value: 00:11:22:33:44:58
        public: true
      - value: 00:11:22:33:44:59
        public: false
```

It's the type of shorthand that's common throughout ESPHome.

**Comment by gitsso1** [comment]
Hi, @shajen . It seems several people have suggested a blacklist option vs only whitelist. Is there a technical reason this can't be implemented alongside work you've already done? Are we misunderstanding the feature (not a developer otherwise I would help) and is there a way to implement blacklist with this PR just not obvious?

Thanks for your work.

**Comment by dseven** [comment]
AFAICT, the ESP GAP API doesn't provide blacklist functionality (only whitelist), so if it was to be implemented, I think it'd have to use some other mechanism.

**Comment by davidcoulson** [comment]
Is there also a mechanism to filter based on RSSI? I have a few BLE proxies so limiting them to -75dB would cut down on noise and traffic from proxies that can barely communicate with a device.

**Comment by dseven** [comment]
@davidcoulson I don't believe so. I don't even know what that would do, since RSSI is going to be changing all the time. I suppose maybe it could filter out broadcast advertisements that are below a threshold.

@shajen Are you still planning on pushing this PR through? Seems it's been stalled for months, while esphome moves on, so this needs rebasing again (doesn't align with 2026.7.4)...

**Comment by shajen** [comment]
> @shajen Are you still planning on pushing this PR through? Seems it's been stalled for months, while esphome moves on, so this needs rebasing again (doesn't align with 2026.7.4)...

The PR has been ready for a long time. I don't know why no one wants to do a review.

**Comment by dseven** [comment]
> > @shajen Are you still planning on pushing this PR through? Seems it's been stalled for months, while esphome moves on, so this needs rebasing again (doesn't align with 2026.7.4)...
> 
> The PR has been ready for a long time. I don't know why no one wants to do a review.

I did have a couple of suggestions (https://github.com/esphome/esphome/pull/14353#issuecomment-4718780185), and there was another suggestion in a post right after mine. Probably none of them are showstoppers, though. Maybe we can twist @bdraco 's arm if you can rebase again.....

BTW, the current changeset seems to be (now) conflicting with the explicit removal of BLE 5.0 support in https://github.com/esphome/esphome/commit/dafc86d960695e8971e8510422365ac7d067d653

**Comment by Entropy512** [comment]
As far as the comments - It looks like a blacklist would have to be implemented in a very different architectural way to the whitelist here, so it makes sense for that to be a separate PR.

Especially since there are use cases where the whitelist alone is highly beneficial.  For example, a single-device bluetooth proxy could use Thread instead of wifi for the backhaul.

@Unfocused As far as that shorthand you mention - can you point to an example of implementing this that could be used as a basis?

**Comment by dseven** [comment]
I agree that blacklist would be a separate feature addition, and shouldn't hold this PR up, but my point was that if there is a chance of such a future addition, I think the configuration naming added for whitelist should be explicitly named - i.e. something like "allowed_mac_addresses" rather than just "mac_address".

**Comment by davidcoulson** [comment]
Following up on the deny-list use case @mtheli raised — I've implemented it in an external component rather than asking for it here, because it turned out to be solvable at the advertisement level for the proxy case specifically: Home Assistant picks a proxy from among those reporting a device, so dropping one MAC's advertisements on a single proxy takes that proxy out of contention for it without turning it into a single-purpose bridge. That covers the bonded-device thrashing case (and esphome/feature-requests#2908) for `bluetooth_proxy` users. I also added an exclusive-allowlist mode that reproduces the observable advertisement behaviour of this PR's whitelist.

**To be clear, that is not a substitute for what you're doing here**, and I don't think this PR is redundant:

- Yours filters in the **BLE controller** (`BLE_SCAN_FILTER_ALLOW_ONLY_WLST`), so non-matching packets never reach the host stack — saving CPU and power, not just network traffic. A host-side filter receives and parses everything before discarding it.
- Yours restricts **which devices may connect** to the ESP32. An advertisement filter has no visibility into that at all. The proxy-level effect above is emergent (HA simply never routes a connection through a proxy that isn't reporting the device) rather than enforced, so an explicit connect request would still go through.
- Yours applies to **every consumer**, including local `esp32_ble_tracker` sensors, not just what the proxy forwards.

The one thing the external component adds is platform coverage: this PR is ESP32-only by construction (`esp_ble_gap_*`), while `bluetooth_proxy` also runs on rp2, bk72xx and ln882x.

So the split looks clean to me: the hardware whitelist for single-purpose bridges and connection security on ESP32, host-side filtering for general-purpose proxies that need to shed noise on any platform. Happy to see this land.

For reference, the external component is [esphome-ble-advert-filter](https://github.com/davidcoulson/esphome-ble-advert-filter), which builds on the advertisement filter hook proposed in #19220 — @bdraco's suggested shape after I initially (and wrongly) tried to put the filtering itself in core in #19219. It's been running across a 60+ proxy deployment at a sustained ~60% advertisement drop rate.

(Written with AI assistance; the testing and the conclusions above are mine.)
