### ISSUE TITLE
esp32_hosted: ESP32-P4 build fails on esp_now.h unless wifi/espnow/BLE is configured (2026.9.0)

### ISSUE THREAD

**Issue by jharris4** [esphome/esphome#19341]
### The problem

On 2026.9.0, an ESP32-P4 config using `esp32_hosted` fails to compile unless it
*also* happens to contain a `wifi:` block, the `espnow` component, or a
Bluetooth component:

    ../src/esphome/components/esp32_hosted/esp_now_hosted.cpp:33:10: fatal error: esp_now.h: No such file or directory

2026.9.0 added `esp_now_hosted.cpp` to `esp32_hosted`. It is guarded only by
`#if defined(CONFIG_IDF_TARGET_ESP32P4)`, so it compiles on every P4 host
whether or not `espnow` is configured, and it includes `<esp_now.h>`. That
header is provided by the built-in IDF `esp_wifi` component, which is listed in
`DEFAULT_EXCLUDED_IDF_COMPONENTS` in `esphome/components/esp32/__init__.py` and
so is filtered out of the `REQUIRES` list generated for `src`.

`esp32_hosted`'s `to_code()` enables the shim for every P4 host
(`add_define("USE_ESP_NOW_HOSTED")`, the two CustomRpc sdkconfig options) but
never calls `include_builtin_idf_component("esp_wifi")` to match.

The build therefore only succeeds when some unrelated component happens to
re-include `esp_wifi`:

- `wifi` -> `request_wifi()` -> `include_builtin_idf_component("esp_wifi")`
- `espnow` -> calls `include_builtin_idf_component("esp_wifi")` directly
- any BLE component -> `request_bluetooth()` -> includes `bt`, whose own
  REQUIRES pulls `esp_wifi` in transitively

This matches the existing comment on the `esp_wifi` entry in that list
("re-included by request_wifi(), espnow; bt pulls it back for BLE builds") --
`esp32_hosted` is a fourth consumer that was not added to it.

Across my 13 ESP32-P4 devices, 5 failed and 8 built fine. The 8 that built only
did so because they had `wifi:` or `bluetooth_proxy:`. Two devices share an
identical Ethernet base config and differ only in that one does
`bluetooth_proxy: !remove` -- that one fails and the other succeeds, which
isolates the dependency cleanly.

The identical file builds on 2026.8.2 (`Successfully compiled program`, flash
29.3%), where `esp_now_hosted.cpp` did not yet exist, and fails on 2026.9.0. So
this is a regression in 2026.9.0, not a pre-existing config problem.

### Which version of ESPHome has the issue?

2026.9.0

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Component causing the issue

esp32_hosted

### YAML Config

```yaml
esphome:
  name: p4-espnow-repro

esp32:
  board: esp32-p4-evboard
  framework:
    type: esp-idf

esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  active_high: true
  clk_pin: GPIO18
  cmd_pin: GPIO19
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17

logger:


That is the complete file -- no `wifi:`, no `ethernet:`, no BLE, no `espnow`.
Compiling it with 2026.9.0 fails; the same file on 2026.8.2 builds.
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2026.9.0
INFO Compiling app... Build path: .esphome/build/p4-espnow-repro
...
[954/997] Building CXX object esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/esp32_hosted/esp_now_hosted.cpp.obj
FAILED: esp-idf/src/CMakeFiles/__idf_src.dir/esphome/components/esp32_hosted/esp_now_hosted.cpp.obj
../src/esphome/components/esp32_hosted/esp_now_hosted.cpp:33:10: fatal error: esp_now.h: No such file or directory
   33 | #include <esp_now.h>         // injected declarations we are now DEFINING
      |          ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Compilation failed because esp_now_hosted.cpp (in "src" component) includes esp_now.h, provided by esp_wifi component(s).
However, esp_wifi component(s) is not in the requirements list of "src".
To fix this, add esp_wifi to PRIV_REQUIRES list of idf_component_register call in .esphome/build/p4-espnow-repro/src/CMakeLists.txt.
ninja failed with exit code 1
```

### Workaround

There is a workaround for this issue, re-including the component from YAML is enough:

    esp32:
      framework:
        type: esp-idf
        advanced:
          include_builtin_idf_components: [esp_wifi]

This only restores header visibility -- it does not enable Wi-Fi. Building the
minimal config above with and without that option on 2026.9.0 produces a
byte-identical `sdkconfig.h`:

    without (fails):  60175 bytes  md5 8837d2a65c379f150e460a8b5f13b90b
    with    (builds): 60175 bytes  md5 8837d2a65c379f150e460a8b5f13b90b

`CONFIG_ESP_WIFI_ENABLED` and `CONFIG_SOC_WIFI_SUPPORTED` are undefined in
both; `CONFIG_ESP_WIFI_REMOTE_ENABLED` is set in both, by `esp32_hosted`. The
resulting `libesp_wifi.a` is 1424 bytes and contains only `dummy_src.c.obj` --
the P4 has no Wi-Fi radio, so the built-in component compiles to a stub.

Also verified on two real devices (one Ethernet + BLE, one Ethernet without).

### Suggested fix

In `esphome/components/esp32_hosted/__init__.py`, in the P4 branch of
`to_code()` that already enables the shim:

    if esp32.get_esp32_variant() == esp32.VARIANT_ESP32P4:
        add_define("USE_ESP_NOW_HOSTED")
        # esp_now_hosted.cpp includes <esp_now.h>, provided by the built-in
        # esp_wifi component, which is excluded by default.
        esp32.include_builtin_idf_component("esp_wifi")
        ...

That matches how `espnow` and `wifi` already declare the same dependency.
