### ISSUE TITLE
I2C software timeout on GPIO19/20 (USB_SERIAL_JTAG pins) — regression since 2026.3.0

### ISSUE THREAD

**Issue by Verstreubulator** [esphome/esphome#15356]
### The problem

I2C communication on GPIO19 (SDA) and GPIO20 (SCL) stopped working after upgrading from ESPHome 2026.2.4 to 2026.3.0. The exact same configuration and hardware that was working just days before now produces continuous `I2C software timeout` errors. Nothing changed except the ESPHome version.

GPIO19 and GPIO20 are shared with the ESP32-S3 USB_SERIAL_JTAG peripheral (USB D- and D+). I2C on other GPIO pairs (e.g., GPIO8/GPIO9) works fine with the same ESPHome version, so this appears to be specific to the USB_SERIAL_JTAG pin conflict.

**Last working version:** ESPHome 2026.2.4 (confirmed working March 18-19, 2026)
**First broken version:** ESPHome 2026.3.0
**Still broken on:** ESPHome 2026.3.1

Tested on two identical Elecrow CrowPanel ESP32-S3 7" V3.0 boards. Both exhibit the same failure.

### Hardware
- **Board:** Elecrow CrowPanel ESP32-S3 7" V3.0 (DIS08070H)
- **MCU:** ESP32-S3-WROOM-1-N4R8 (4MB Flash, 8MB PSRAM)
- **I2C devices:** GT911 touch controller (0x5D), PCA9557 I/O expander (0x18)
- **I2C pins:** SDA=GPIO19, SCL=GPIO20 (shared with USB_SERIAL_JTAG D- and D+)

### What I've tried — all produce I2C software timeout
- ESPHome 2026.3.0 and 2026.3.1 with ESP-IDF 5.5.3 (default)
- Pinned ESP-IDF to 5.4.2
- USB flash with factory image (new bootloader)
- Added constructor to disable USB_SERIAL_JTAG pull-up on GPIO19
- Added GPIO pin reconfiguration (PIN_FUNC_SELECT, pull-ups)
- Multiple full power cycles between attempts
- Removed all custom code, restored exact previously-working config

### Evidence this is a regression
- The **exact same YAML config** worked on ESPHome 2026.2.4
- The **exact same hardware** — no physical changes
- **Two identical CrowPanel V3.0 units** both exhibit the same failure
- The **Elecrow factory demo firmware** (Arduino) has working I2C touch on this exact hardware
- A **Waveshare ESP32-S3-Touch-LCD-7** using GPIO8/GPIO9 for I2C works perfectly with ESPHome 2026.3.1

### Suspected root cause
The new `esp_driver_i2c` API (`i2c_master_*` functions) may not properly release the USB_SERIAL_JTAG peripheral's hold on GPIO19/20 before initializing I2C.

### Which version of ESPHome has the issue?

2026.3.0 and 2026.3.1 (last working: 2026.2.4)

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Component causing the issue

i2c

### YAML Config

```yaml
esphome:
  name: crowpanel-test
  platformio_options:
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 4MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    advanced:
      execute_from_psram: true

psram:
  mode: octal
  speed: 80MHz

logger:
  level: DEBUG
  hardware_uart: UART0

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  - id: touch_i2c
    sda: 19
    scl: 20
    scan: false
    frequency: 400000

touchscreen:
  - platform: gt911
    id: my_touchscreen
    i2c_id: touch_i2c
    address: 0x5D
    update_interval: 50ms
```

### Anything in the logs that might be useful for us?

```txt
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce2820,len:0x14f0
load:0x403c8700,len:0xd24
load:0x403cb700,len:0x2f3c
entry 0x403c891c
I (24) boot: ESP-IDF 5.5.3 2nd stage bootloader
I (25) boot: compile time Apr  1 2026 13:46:38
I (25) boot: Multicore bootloader
I (25) boot: chip revision: v0.2
I (28) boot: efuse block revision: v1.3
I (31) boot.esp32s3: Boot SPI Speed : 80MHz
I (35) boot.esp32s3: SPI Mode       : DIO
I (39) boot.esp32s3: SPI Flash Size : 4MB
I (43) boot: Enabling RNG early entropy source...
I (47) boot: Partition Table:
I (50) boot: ## Label            Usage          Type ST Offset   Length
I (56) boot:  0 otadata          OTA data         01 00 00009000 00002000
I (62) boot:  1 phy_init         RF data          01 01 0000b000 00001000
I (69) boot:  2 app0             OTA app          00 10 00010000 001c0000
I (75) boot:  3 app1             OTA app          00 11 001d0000 001c0000
I (82) boot:  4 nvs              WiFi data        01 02 00390000 0006d000
I (89) boot: End of partition table
I (92) boot: No factory image, trying OTA 0
I (303) boot: Loaded app from partition at offset 0x10000
I (307) boot: Set actual ota_seq=1 in otadata[0]
I (308) boot: Disabling RNG early entropy source...

[W][esp-idf:000]: E (2381) i2c.master: I2C software timeout
[W][esp-idf:000]: E (2643) i2c.master: I2C software timeout
[W][esp-idf:000]: E (3432) i2c.master: I2C software timeout
[W][esp-idf:000]: E (3853) i2c.master: I2C software timeout
[W][esp-idf:000]: E (4693) i2c.master: I2C software timeout
[W][esp-idf:000]: E (6343) i2c.master: I2C software timeout
[W][esp-idf:000]: E (7000) i2c.master: I2C software timeout
[W][esp-idf:000]: E (7262) i2c.master: I2C software timeout
[W][esp-idf:000]: E (9788) i2c.master: I2C software timeout
[W][esp-idf:000]: E (10315) i2c.master: I2C software timeout
[W][esp-idf:000]: E (11743) i2c.master: I2C software timeout
[W][esp-idf:000]: E (12683) i2c.master: I2C software timeout
[W][esp-idf:000]: E (13369) i2c.master: I2C software timeout
[W][esp-idf:000]: E (13790) i2c.master: I2C software timeout
[W][esp-idf:000]: E (13999) i2c.master: I2C software timeout
[W][esp-idf:000]: E (14308) i2c.master: I2C software timeout
[W][esp-idf:000]: E (14623) i2c.master: I2C software timeout
[W][esp-idf:000]: E (14885) i2c.master: I2C software timeout
[W][esp-idf:000]: E (17479) i2c.master: I2C software timeout
[W][esp-idf:000]: E (17742) i2c.master: I2C software timeout
[W][esp-idf:000]: E (20123) i2c.master: I2C software timeout
(continues indefinitely)

Build environment:
HARDWARE: ESP32S3 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50503.0 (5.5.3)
 - toolchain-xtensa-esp-elf @ 14.2.0+20251107
 - tool-esptoolpy @ 5.1.2
Chip: ESP32-S3 (QFN56) (revision v0.2), Embedded PSRAM 8MB
```

### Related issues

- #13307 — CrowPanel V3.0 touch not working (different root cause: PCA9557 manipulation, not I2C driver)
- esphome/esphome-devices#1494 — Device page submission for this board (config worked before this regression)

**Comment by swoboda1337** [comment]
Might be https://github.com/esphome/esphome/pull/13628

**Comment by swoboda1337** [comment]
Can try:
```
  esp32:
    framework:
      type: esp-idf
      sdkconfig_options:
        CONFIG_ESP_CONSOLE_SECONDARY_NONE: y
```

**Comment by Verstreubulator** [comment]
Thank you Swoboda1337! I will try this and report back very soon!

**Comment by Verstreubulator** [comment]
### Additional test: disabling USB_SERIAL_JTAG via sdkconfig

Tested whether the USB_SERIAL_JTAG secondary console is holding GPIO19/20 by adding these sdkconfig options:

```yaml
esp32:
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP_CONSOLE_SECONDARY_NONE: "y"
      CONFIG_USJ_NO_AUTO_LS_EN: "y"
```

Combined with a pre-`app_main()` constructor (`__attribute__((constructor(101)))`) that clears `USB_SERIAL_JTAG_USB_PAD_ENABLE`, resets GPIO19/20 to `PIN_FUNC_GPIO`, enables input + pull-ups, and disables pull-downs.

**Result:** Same `E (xxxx) i2c.master: I2C software timeout` starting ~1.8s after boot, repeating indefinitely. No change in behavior.

**Updated workaround table:**

| Attempt | Result |
|---------|--------|
| `CONFIG_ESP_CONSOLE_SECONDARY_NONE: "y"` | I2C software timeout |
| `CONFIG_USJ_NO_AUTO_LS_EN: "y"` | I2C software timeout |
| Both options + runtime USB pad disable constructor | I2C software timeout |

This rules out the USB_SERIAL_JTAG console/peripheral as the cause. The issue appears to be in the `esp_driver_i2c` (`i2c_master`) driver itself not properly acquiring GPIO19/20 when they overlap with USB_SERIAL_JTAG pins, regardless of whether the USB peripheral is active.

ESPHome 2026.2.4 (which used the legacy `i2c_driver_*` API) handles these pins correctly on the same hardware.

**Comment by swoboda1337** [comment]
We switched to the new driver a long time ago, like 6 months ago.

Can try:
```
esphome:
  on_boot:
    - priority: 1001
      then:
        - lambda: |-
            gpio_reset_pin((gpio_num_t)19);
            gpio_reset_pin((gpio_num_t)20);
```

**Comment by Verstreubulator** [comment]
### Workaround testing results (April 2-3, 2026)

First off — huge thank you to the ESPHome team for all the incredible work you do. This project is amazing and I'm grateful for every release. I know GPIO19/20 on ESP32-S3 is a tricky edge case, and I hope these detailed findings are helpful in tracking down the root cause.

I ran through every user-level workaround I could think of to try to get I2C working on GPIO19/20 with the new `esp_driver_i2c` driver. None of them resolved the issue, but the results may help narrow things down.

**Hardware:** Elecrow CrowPanel ESP32-S3 7" V3.0 (DIS08070H), 2 identical units
**ESPHome:** 2026.3.1 and 2026.3.2
**ESP-IDF:** 5.5.3
**I2C devices:** GT911 touch (0x5D), PCA9557 I/O expander (0x18)
**I2C pins:** SDA=GPIO19, SCL=GPIO20 (shared with USB_SERIAL_JTAG)

#### Build-time sdkconfig options

| Option | Purpose | Result |
|--------|---------|--------|
| `CONFIG_ESP_CONSOLE_SECONDARY_NONE: "y"` | Disable secondary USB_SERIAL_JTAG console | I2C software timeout (continuous) |
| `CONFIG_USJ_NO_AUTO_LS_EN: "y"` | Disable USB_SERIAL_JTAG auto light-sleep clock | I2C software timeout (continuous) |
| Both options combined | Belt and suspenders | I2C software timeout (continuous) |

#### Pre-app_main() static constructor (usb_disable.h)

Runs as `__attribute__((constructor(101)))` before ESPHome `app_main()`:

| Approach | Result |
|----------|--------|
| Clear `USB_SERIAL_JTAG_USB_PAD_ENABLE` + `PIN_FUNC_SELECT` + pull-ups | I2C software timeout (continuous) |
| Above + `periph_module_disable(PERIPH_USB_MODULE)` (kill peripheral clock) + GPIO matrix output disconnect | Inconsistent — zero timeouts on partial recompile, continuous timeouts on full recompile (appears binary layout dependent) |

#### on_boot gpio_reset_pin() at various priorities

`gpio_reset_pin()` is a higher-level ESP-IDF API that disconnects peripheral signal routing, resets IO MUX, and clears the GPIO matrix.

| Priority | When it runs | Result |
|----------|-------------|--------|
| 1100 | Before hardware init | I2C software timeout (continuous) |
| 1001 | After hardware init, before component setup | **1 timeout then bus clean** (on partial recompile — not consistent on full builds) |
| 800 | Between hardware init (900) and I2C setup (600) | 2 timeouts then bus clean, GT911 marked FAILED |
| 600.1 | Just after I2C setup (600) | 2 timeouts then bus clean, GT911 marked FAILED |

#### Post-setup retry strategies (priority -100 or 200)

After the initial setup fails, I tried various ways to re-initialize the touchscreen:

| Approach | Result |
|----------|--------|
| `reset_to_construction_state()` + `setup()` on both I2C and touchscreen | I2C software timeout (continuous) — re-running I2C setup re-acquires the pins |
| `reset_to_construction_state()` + `setup()` on touchscreen only (skip I2C) | GT911 still FAILED — setup() internally uses the I2C driver which re-acquires the pins |
| `gpio_set_direction(OD)` + `gpio_set_pull_mode(PULLUP)` + touchscreen retry | GT911 still FAILED — same root cause |
| `gpio_reset_pin()` + `delay(200ms)` + touchscreen retry | I2C software timeout (continuous) |
| Force component state from FAILED to LOOP via struct hack (skip setup entirely) | I2C timeouts continuous on full build |

#### What I observed

1. **`gpio_reset_pin()` at priority 1001 came closest** — on partial recompiles it produced only 1 I2C timeout, after which the bus was completely clean. However, this wasn't consistent on full recompiles, which suggests timing or binary layout may play a role.

2. **Re-running the I2C driver's `setup()` re-acquires the pins.** It seems like the `esp_driver_i2c` master driver's initialization is where GPIO19/20 get claimed from USB_SERIAL_JTAG, so fixing the pins before or after doesn't stick.

3. **Display rendering works perfectly** — only I2C is affected. A Waveshare board using GPIO8/GPIO9 for I2C works fine with the same ESPHome version, confirming this is specific to the USB_SERIAL_JTAG pin overlap.

4. **The exact same config works perfectly on ESPHome 2026.2.4** (which used the legacy `i2c_driver_*` API). Same hardware, same wiring, same YAML.

#### My best guess

It looks like the new `esp_driver_i2c` driver may not be fully releasing the USB_SERIAL_JTAG peripheral's hold on GPIO19/20 during initialization, whereas the legacy driver handled this correctly. I could be wrong about the root cause, but hopefully all this testing data helps!

Thank you again for everything you all do for this community. I'm happy to test any patches or ideas if that would be helpful.

**Comment by swoboda1337** [comment]
2026.2.4 used the same driver, ESPHome hasn't used the legacy driver in a very long time. 

We moved to the new driver last summer https://github.com/esphome/esphome/pull/8483

**Comment by Verstreubulator** [comment]
Thank you for the correction — I appreciate you pointing that out. I was mistaken about the driver change being the cause.

That said, the same config and hardware works perfectly on 2026.2.4 and fails on 2026.3.0. Something changed between those two versions that affects I2C on GPIO19/20 specifically.

Would you happen to know what changed between 2026.2.4 and 2026.3.0 that could affect I2C or GPIO19/20 handling? Was there an ESP-IDF version bump, or any changes to how the I2C component initializes pins?

Happy to test anything that might help narrow it down.

**Comment by swoboda1337** [comment]
I believe we moved from IDF 5.5.2 to IDF 5.5.3.1, you can try 5.5.2 and:
```
esp32:
  framework:
    type: esp-idf
    version: 5.5.4
    platform_version: https://github.com/pioarduino/platform-espressif32.git#develop
``` 
maybe also:
```
esphome:
  on_boot:
    - priority: 1001
      then:
        - lambda: |-
            gpio_func_sel((gpio_num_t)19, PIN_FUNC_GPIO);
            gpio_func_sel((gpio_num_t)20, PIN_FUNC_GPIO);
```

**Comment by Verstreubulator** [comment]
Thank you so much for the correction on the driver history and for taking the time to suggest things to try — I really appreciate it. I know you're busy and it means a lot that you're helping with this.

I went ahead and tested both suggestions. Here's what I found:

#### `gpio_func_sel()` at priority 1001

I wasn't able to get `gpio_func_sel` to compile on ESP-IDF 5.5.3 or 5.5.4 — it gives `'gpio_func_sel' was not declared in this scope`. I'm probably just missing the right header include — would you mind pointing me to which one I need?

In the meantime I tried `PIN_FUNC_SELECT(IO_MUX_GPIOxx_REG, PIN_FUNC_GPIO)` as a substitute since I believe it does the same IO MUX function select, but unfortunately that didn't resolve the timeouts either.

#### ESP-IDF version testing

| Version | Result |
|---------|--------|
| 5.5.3 (ESPHome default) | I2C software timeout (continuous) |
| 5.5.4 + `platform_version: pioarduino develop` | I2C software timeout (continuous) — same behavior as 5.5.3 |
| 5.5.2 + `platform_version: pioarduino develop` | Build fails — toolchain mismatch (`Tool doesn't match supported version from list ['esp-14.2.0_20251107']`). Cleared PlatformIO cache and retried, same result. The `develop` platform appears to ship a toolchain that's too new for 5.5.2. |

#### Other workarounds I tried

In case it's useful, here's everything else I tested during this session. None of them resolved the I2C timeouts on GPIO19/20, but maybe the patterns help narrow things down:

**Build-time sdkconfig options:**

| Option | Result |
|--------|--------|
| `CONFIG_ESP_CONSOLE_SECONDARY_NONE: "y"` | I2C software timeout (continuous) |
| `CONFIG_USJ_NO_AUTO_LS_EN: "y"` | I2C software timeout (continuous) |

**Pre-app_main() static constructor (`usb_disable.h`):**
- Clear `USB_SERIAL_JTAG_USB_PAD_ENABLE` + `PIN_FUNC_SELECT` + pull-ups → timeout
- Above + `periph_module_disable(PERIPH_USB_MODULE)` + GPIO matrix disconnect → inconsistent (appeared to work on a partial recompile but not on a full build)

**on_boot `gpio_reset_pin()` at various priorities:**

| Priority | Result |
|----------|--------|
| 1100 (before hardware init) | Timeout (continuous) |
| 1001 (after hardware init) | 1 timeout then bus clean on partial recompile, not consistent on full build |
| 800 (before I2C setup) | 2 timeouts then clean, GT911 marked FAILED |
| 600.1 (just after I2C setup) | 2 timeouts then clean, GT911 marked FAILED |

**Post-setup retry strategies:**
- Re-running `setup()` on I2C + touchscreen → continuous timeouts (I2C driver re-acquires the pins)
- Re-running `setup()` on touchscreen only → still FAILED (setup uses I2C driver internally)
- Manual GPIO direction/pull-up configuration + retry → still FAILED
- Forcing component state from FAILED to LOOP → I2C timeouts on full build

One interesting finding: `gpio_reset_pin()` at priority 1001 sometimes produced only a single timeout, after which the bus was completely clean. But the GT911 had already been marked FAILED by that point, and any attempt to re-run `setup()` re-triggered the I2C driver which re-acquired the pins. It felt like we were close but couldn't quite get there.

I'm happy to retry 5.5.2 if you know the right platform version to pair with it, and also happy to retry `gpio_func_sel` once I know the right header. Thank you again for all the time and effort you put into ESPHome — it's an incredible project and I'm grateful for everything you do!

**Comment by swoboda1337** [comment]
For 5.5.2 you don't need to list a platform just remove it. It's knows which one to use

**Comment by Verstreubulator** [comment]
Thank you so much for the suggestions and for taking the time to help — it means a lot and I'm really grateful. I have great news: I found a working fix!

I hope you don't mind that I went digging through the ESP-IDF source code to try to understand what's happening — I know that's your territory and I apologize if I'm overstepping. I just wanted to be as helpful as possible and not waste your time with vague reports.

#### The Fix

Adding `usb_serial_jtag_ll_phy_enable_pad(false)` in a pre-`app_main()` constructor fully resolves the I2C timeout on GPIO19/20. I've confirmed this on **two separate CrowPanel ESP32-S3 7" units**, both with clean full builds on ESPHome 2026.3.2 / ESP-IDF 5.5.3. Zero I2C timeouts, GT911 touch working perfectly on both boards.

Here's the working header file, included via `esphome.includes`:

```c
#pragma once

#include "soc/usb_serial_jtag_reg.h"
#include "soc/io_mux_reg.h"
#include "hal/usb_serial_jtag_ll.h"

static __attribute__((constructor(101))) void disable_usb_serial_jtag_phy() {
    // Disable USB PHY pad control (releases GPIO19/20 from USB peripheral)
    usb_serial_jtag_ll_phy_enable_pad(false);

    // Clear USB pad enable bit
    CLEAR_PERI_REG_MASK(USB_SERIAL_JTAG_CONF0_REG, USB_SERIAL_JTAG_USB_PAD_ENABLE);

    // Disable D+ pull-up (GPIO20) — persists even after GPIO reconfig
    CLEAR_PERI_REG_MASK(USB_SERIAL_JTAG_CONF0_REG, USB_SERIAL_JTAG_DP_PULLUP);

    // Reset GPIO19/20 to normal GPIO function with pull-ups for I2C
    PIN_FUNC_SELECT(IO_MUX_GPIO19_REG, PIN_FUNC_GPIO);
    PIN_FUNC_SELECT(IO_MUX_GPIO20_REG, PIN_FUNC_GPIO);
    PIN_INPUT_ENABLE(IO_MUX_GPIO19_REG);
    PIN_INPUT_ENABLE(IO_MUX_GPIO20_REG);
    REG_SET_BIT(IO_MUX_GPIO19_REG, FUN_PU);
    REG_SET_BIT(IO_MUX_GPIO20_REG, FUN_PU);
    REG_CLR_BIT(IO_MUX_GPIO19_REG, FUN_PD);
    REG_CLR_BIT(IO_MUX_GPIO20_REG, FUN_PD);
}
```

#### What I found in the source (sorry for the deep dive!)

Please forgive me for poking around in the code — I was just trying to understand why my earlier attempts weren't working.

I noticed that the I2C driver's `s_hp_i2c_pins_config()` in `i2c_common.c` calls `gpio_func_sel()`, which goes through `gpio_ll_func_sel` in the ESP32-S3 HAL. That function already has explicit code to clear `USB_SERIAL_JTAG_USB_PAD_ENABLE` for GPIO19/20, so the I2C driver *is* trying to release the pins — which makes sense.

The issue seems to be that clearing `USB_PAD_ENABLE` alone isn't enough. The USB PHY pad appears to be a separate hardware-level control that sits between the physical pin and the GPIO matrix. When the PHY pad is active, the USB peripheral still has priority over GPIO matrix routing even with `USB_PAD_ENABLE` cleared. The call that makes the difference is `usb_serial_jtag_ll_phy_enable_pad(false)`, which fully disables the PHY's control of the pins. The `USB_SERIAL_JTAG_DP_PULLUP` bit also needs clearing since it maintains a pull-up on GPIO20 (D+) that persists through GPIO reconfiguration and can interfere with I2C signaling.

#### What might have changed

Looking at the ESP-IDF changelog between 5.5.2 and 5.5.3, I noticed commit `2f63581` (related to esp-idf#17488) changed how the USB DP pin and peripheral clocks are managed during startup. I *think* this might have changed the behavior so the USB PHY stays more aggressively enabled, but I could absolutely be wrong about that — you'd know far better than me.

#### Regarding `gpio_func_sel`

I wasn't able to get `gpio_func_sel` to compile directly in a lambda — it gives `'gpio_func_sel' was not declared in this scope` on both ESP-IDF 5.5.3 and 5.5.4. I'm probably just missing the right header include. But it turned out to be a moot point since the fix needed to happen at the PHY level rather than just the IO MUX level.

#### ESP-IDF version testing

For completeness, I confirmed the timeout occurs on all 5.5.x versions I could test (without the fix):

| Version | Result |
|---------|--------|
| 5.5.2 | I2C software timeout |
| 5.5.3 (default) | I2C software timeout |
| 5.5.4 | I2C software timeout |

The fix was tested and confirmed working on 5.5.3 across two boards.

#### A humble suggestion

I don't want to overstep, but in case it's helpful — it might be worth considering having the I2C component detect when GPIO19/20 are being used on ESP32-S3 and automatically call `usb_serial_jtag_ll_phy_enable_pad(false)` during pin setup. But you all know the codebase far better than I do, so please take that with a grain of salt.

Thank you again for everything. The time you spent pointing me in the right direction is what got me to this fix. I'm so grateful for all the work you put into ESPHome — it's an incredible project and this community is lucky to have you!!! I love EspHome and use it almost daily!

**Comment by ssieb** [comment]
There's no problem with you looking through the source code.  Nobody's claiming that territory!
This does seem a bit like a bug in esp-idf, but at least there's a way to work around it.

**Comment by Verstreubulator** [comment]
I think this is clearly a bug in ESP-IDF too. I think I might also know how to fix it. Right now, I don't know how to report this bug to Esspressif and will work on this tomorrow.

I am still learning how GitHub works. I do not fully understand yet. If you need to close out this issue, please feel free to do so. My problem is solved. Hopefully this information will be useful to others. I have documented everything in a pull request at esphome/esphome-devices#1494.

Anyway, thank you so much! You have been super helpful in this adventure and I really appreciate it! Without HA and EspHome, I am pretty sure I would have turned to a life of crime! You are doing a great thing for the benefit of society and the world at large! I hope someday to attain the skills necessary to do something similar and am working on my first full fledged HA integration right now. Then, fools like me can pester a fool like me to fix their petty problems. Thanks again!

**Comment by Batman-LV** [comment]
## Confirmed fix: disable the USB-Serial-JTAG PHY pad before I2C inits

I hit this exact regression on a CrowPanel ESP32-S3 7" V3.0 (DIS08070H) and have a working fix that doesn't require pinning ESPHome or ESP-IDF. Sharing it here in case it helps others and as a possible basis for an upstream patch.

**TL;DR:** calling `usb_serial_jtag_ll_phy_enable_pad(false)` from a global C++ constructor (static-init time, before `app_main()`) releases GPIO19/20 from the USB-Serial-JTAG peripheral so the new `esp_driver_i2c` API can drive them. After this, **zero I2C timeouts** and the GT911 communicates normally. Confirmed on ESPHome 2026.6.2 / ESP-IDF 5.5.3.

This matches the suspected root cause in the original report: the new I2C driver doesn't release the USB_SERIAL_JTAG hold on GPIO19/20, and the pad has to be disabled *early* — a high-priority component `setup()` is too late, because the I2C bus configures those pads first. A static constructor runs before `app_main()`, which is early enough.

### The fix as an `includes:` header

`usb_jtag_release.h` (place next to your device YAML):

```cpp
#pragma once
// Releases GPIO19/20 from the USB-Serial-JTAG peripheral so I2C works on
// ESP32-S3 boards that route I2C over the USB D-/D+ pins (e.g. CrowPanel
// V3.0). A global object's constructor runs at static-init time — before
// app_main() and before the I2C driver grabs the pads.

#ifdef USE_ESP32
#include "hal/usb_serial_jtag_ll.h"

namespace {
struct UsbJtagReleaser {
  UsbJtagReleaser() {
    usb_serial_jtag_ll_phy_enable_pad(false);
  }
};
static UsbJtagReleaser g_usb_jtag_releaser;
}  // namespace
#endif
```

YAML:

```yaml
esphome:
  name: crowpanel-7
  includes:
    - usb_jtag_release.h

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 4MB
  framework:
    type: esp-idf

logger:
  hardware_uart: UART0   # keep logs off the USB-JTAG pins

i2c:
  - id: touch_i2c
    sda: 19
    scl: 20
    scan: false
    frequency: 400000
```

### Before / after

Before — the familiar flood:

```
[W][esp-idf:000]: E (2381) i2c.master: I2C software timeout
[W][esp-idf:000]: E (2643) i2c.master: I2C software timeout
(continues indefinitely)
```

After — clean bus, GT911 found:

```
[C][gt911.touchscreen:153]: GT911 Touchscreen:
[C][gt911.touchscreen:154]:   Address: 0x14
```

No more `I2C software timeout` at all.

### Notes / caveats

- This is the same call ESP-IDF itself uses when reclaiming the USB-Serial-JTAG pads for GPIO; doing it from a static constructor is just the earliest hook available in an ESPHome project without patching the i2c component.
- An external component with a very high `setup_priority` is **not** early enough on its own — the I2C bus had already configured the pads by the time the component's `setup()` ran in my testing. The static constructor is what made the difference.
- A proper upstream fix would presumably live in the esp32 i2c component: release the USB-Serial-JTAG pad hold on GPIO19/20 before `i2c_new_master_bus()`. Happy to test a patched build if a maintainer wants to put one together (cc @Swoboda1337, since you suggested the pad-disable direction earlier in this thread).

### Separate, board-specific GT911 note (not part of this bug)

For anyone landing here from a CrowPanel V3.0: once the bus works, you may still see the GT911 come up at `0x14` instead of `0x5D` and throw `Calibration error` (config registers read back as zeros). That's a **separate** GPIO38 strapping behavior, not part of this I2C regression — the units that come up at `0x5D` read calibration fine. Worth keeping the two issues distinct so this thread stays focused on the I2C driver problem.

---

Full disclosure: I worked through the low-level debugging (ESP-IDF internals, the component lifecycle timing, the GT911 driver behavior) with substantial help from Claude (Anthropic's AI). The results here are tested on real hardware — I just want to be transparent about how I got to them.

**Comment by Verstreubulator** [comment]
No problem! I was just trying to be helpful. If this can no longer meet that goal, please feel free to close it. My problems persist but my own solution solves them for me. I have no idea how to address ESP-IDF issues and bugs. Thanks very much for everything!

**Comment by ssieb** [comment]
It sounds like it should be added to the i2c component, but it should also work in an `on_boot:` at priority 1001.
